Shivkumar/LoginSystem/LoginSystem/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace LoginSystem.Models
{
    public class Person
    {
        [Required(ErrorMessage ="please enter a unique Login Name")]
    
        public string LoginName { set; get; }

        [Required(ErrorMessage = "Please enter password")]
        [DataType(DataType.Password)]
        public string Password { set; get; }

        [Required(ErrorMessage = "Please enter confirm password")]
        [Compare("Password", ErrorMessage = "Password and confirm password should be the same")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { set; get; }

        

        [Required(ErrorMessage ="Please enter Full name")]
        [DataType(DataType.Text)]
        public string FullName { set; get; }

        [Required(ErrorMessage ="Please enter valid email id")]
        [DataType(DataType.EmailAddress,ErrorMessage ="Enter valid email id")]
        public string EmailId { set; get; }

        public int CityId { set; get; }

        [Required(ErrorMessage ="Please enter mobile number")]
        [DataType(DataType.PhoneNumber,ErrorMessage ="Please enter valid phone number")]
        public long Phone { set; get; }

        internal static void InsertPersons(Person obj)
        {

            SqlConnection con = new SqlConnection();
            con.ConnectionString = @"Data Source = (localdb)\MSSQLLocalDB; Initial Catalog = ShivkumarDB; Integrated Security = True; Connect Timeout = 30; Encrypt = False; TrustServerCertificate = False; ApplicationIntent = ReadWrite; MultiSubnetFailover = False";

            try
            {
                con.Open();

                SqlCommand cmdInsert = new SqlCommand();
                cmdInsert.Connection= con;
                cmdInsert.CommandType = System.Data.CommandType.StoredProcedure;
                cmdInsert.CommandText = "InsertPerson";

                cmdInsert.Parameters.AddWithValue("@LoginName", obj.LoginName);
                cmdInsert.Parameters.AddWithValue("@Password", obj.Password);
                cmdInsert.Parameters.AddWithValue("@FullName", obj.FullName);
                cmdInsert.Parameters.AddWithValue("@EmailId", obj.EmailId);
                cmdInsert.Parameters.AddWithValue("@CityId", obj.CityId);
                cmdInsert.Parameters.AddWithValue("@Phone", obj.Phone);

                cmdInsert.ExecuteNonQuery();
            }
            catch
            {

            }
            finally
            {
                con.Close();
            }
        }

        internal static void UpdatePerson(Person obj)
        {

            SqlConnection con = new SqlConnection();
            con.ConnectionString = @"Data Source = (localdb)\MSSQLLocalDB; Initial Catalog = ShivkumarDB; Integrated Security = True; Connect Timeout = 30; Encrypt = False; TrustServerCertificate = False; ApplicationIntent = ReadWrite; MultiSubnetFailover = False";

            try
            {
                con.Open();

                SqlCommand cmdUpdate = new SqlCommand();
                cmdUpdate.Connection = con;
                //cmdUpdate.CommandType = System.Data.CommandType.Text;
                //cmdUpdate.CommandText = "update Persons set FullName=@FullName ,EmailId=@EmailId , CityId=@CityId ,Phone=@Phone where LoginName=@LoginName";

                cmdUpdate.CommandType = System.Data.CommandType.StoredProcedure;
                cmdUpdate.CommandText = "UpdatePerson";

                cmdUpdate.Parameters.AddWithValue("@LoginName", obj.LoginName);
                cmdUpdate.Parameters.AddWithValue("@FullName", obj.FullName);
                cmdUpdate.Parameters.AddWithValue("@EmailId", obj.EmailId);
                cmdUpdate.Parameters.AddWithValue("@CityId", obj.CityId);
                cmdUpdate.Parameters.AddWithValue("@Phone", obj.Phone);

                cmdUpdate.ExecuteNonQuery();
            }
            catch
            {

            }
            finally
            {
                con.Close();
            }


        }

        public bool isActive { set; get; }

        internal static bool IsValidPerson(Person obj)
        {
            SqlConnection con = new SqlConnection();
            con.ConnectionString = @"Data Source = (localdb)\MSSQLLocalDB; Initial Catalog = ShivkumarDB; Integrated Security = True; Connect Timeout = 30; Encrypt = False; TrustServerCertificate = False; ApplicationIntent = ReadWrite; MultiSubnetFailover = False";

            try
            {
                con.Open();

                SqlCommand cmdValid = new SqlCommand();
                cmdValid.Connection = con;
                cmdValid.CommandType = System.Data.CommandType.Text;
                cmdValid.CommandText = "select count(*) from Persons where LoginName=@LoginName and Password=@Password";

                cmdValid.Parameters.AddWithValue("@LoginName", obj.LoginName);
                cmdValid.Parameters.AddWithValue("@Password", obj.Password);

                int val = (int)cmdValid.ExecuteScalar();

                if (val == 0)
                {
                    return false;
                }
                else
                {
                    return true;
                }
            
            }
            catch
            {

            }
            finally
            {
                con.Close();
            }

            return false;
        }

        internal static Person GetSinglePerson(string name)
        {
            Person person = new Person();
            SqlConnection con = new SqlConnection();
            con.ConnectionString = @"Data Source = (localdb)\MSSQLLocalDB; Initial Catalog = ShivkumarDB; Integrated Security = True; Connect Timeout = 30; Encrypt = False; TrustServerCertificate = False; ApplicationIntent = ReadWrite; MultiSubnetFailover = False";

            try
            {
                con.Open();

                SqlCommand cmdSingle = new SqlCommand();
                cmdSingle.Connection = con;
                cmdSingle.CommandType = System.Data.CommandType.Text;
                cmdSingle.CommandText = "select * from Persons where LoginName=@LoginName";

                cmdSingle.Parameters.AddWithValue("@LoginName", name);

                SqlDataReader dr = cmdSingle.ExecuteReader();

                while (dr.Read())
                {
                    person.LoginName = (string)dr["LoginName"];
                    person.FullName = (string)dr["FullName"];
                    person.EmailId = (string)dr["EmailId"];
                    person.CityId = (int)dr["CityId"];
                    person.Phone = (long)dr["Phone"];

                }
                dr.Close();
            }
            catch
            {

            }
            finally
            {
                con.Close();
            }

            return person;
        }
    }
}

Shivkumar/LoginSystem/LoginSystem/Controllers/PersonsController.cs
using LoginSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginSystem.Controllers
{
    public class PersonsController : Controller
    {
        // GET: Persons
        public ActionResult Index()
        {
            return View();
        }

        // GET: Persons/Details/5
        public ActionResult Details()
        {
            string name = (string)Session["LoggedPerson"];
            Person person = Person.GetSinglePerson(name);
            return View(person);
        }


        [HttpPost]
        public ActionResult Details(string logout)
        {
            if (!string.IsNullOrEmpty(logout))
            {
                return RedirectToAction("Logout");
            }
            string name = (string)Session["LoggedPerson"];
            Person obj = Person.GetSinglePerson(name);
            return View(obj);

        }


        // GET: Persons/Create
        public ActionResult Create()

        {
            List<City> cities = City.GetAllCities();
            List<SelectListItem> objCity = new List<SelectListItem>();
            foreach (var item in cities)
            {
                objCity.Add(new SelectListItem { Text=item.CityName, Value=item.CityId.ToString()});
            }
            ViewBag.Cities = objCity;
            return View();
        }

        // POST: Persons/Create
        [HttpPost]
        public ActionResult Create(Person obj)
        {
            try
            {
                // TODO: Add insert logic here

                Person.InsertPersons(obj);

                return RedirectToAction("Login");
            }
            catch
            {
                return RedirectToAction("Create");
            }
        }

        // GET: Persons/Edit/5
        public ActionResult Edit(string id)
        {           
            Person person = Person.GetSinglePerson(id);
            List<City> cities = City.GetAllCities();
            List<SelectListItem> objCity = new List<SelectListItem>();
            foreach (var item in cities)
            {
                objCity.Add(new SelectListItem { Text = item.CityName, Value = item.CityId.ToString() });
            }
            ViewBag.Cities = objCity;
            return View(person);
        }

        // POST: Persons/Edit/5
        [HttpPost]
        public ActionResult Edit(Person obj)
        {
            try
            {
                // TODO: Add update logic here
                Person.UpdatePerson(obj);
                return RedirectToAction("Details");
            }
            catch
            {
                return View();
            }
        }

        // GET: Persons/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Persons/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //===============================================================

       

        // GET: Persons/Login
        public ActionResult Login()
        {
            HttpCookie objCookie = Request.Cookies["PersonLogin"];
            if (objCookie == null)
            {

                return View();
            }
            else
            {
                
                Session["LoggedPerson"] = objCookie.Value;
                return RedirectToAction("Details");
            }

           

        }

        // POST: Persons/Login
        [HttpPost]
        public ActionResult Login(Person obj)
        {
            try
            {
                // TODO: Add insert logic here

                bool isValidPerson = Person.IsValidPerson(obj);

                if (isValidPerson)
                {
                    if (obj.isActive)
                    {
                        HttpCookie objCookie = new HttpCookie("PersonLogin");
                        objCookie.Expires = DateTime.Now.AddDays(1);
                        objCookie.Value = obj.LoginName;
                        Response.Cookies.Add(objCookie);
                        
                    }
                    Session["LoggedPerson"] = obj.LoginName;
                    return RedirectToAction("Details");
                }
                else
                {
                    return RedirectToAction("Login");
                }
                
            }
            catch
            {
                return View();
            }
        }

        
        public ActionResult Logout()
        {
            Session.Abandon();
            HttpCookie objCookie = new HttpCookie("PersonLogin");
            objCookie.Expires = DateTime.Now.AddDays(-1);
            Response.Cookies.Add(objCookie);

            return RedirectToAction("Login");
        }

        [ChildActionOnly]
        public ActionResult PartialView1()
        {
            return View();
        }
    }
}

Shivkumar/LoginSystem/LoginSystem/Views/Persons/Create.cshtml
@model LoginSystem.Models.Person

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/CustomLayout.cshtml";
}

<h2>Register New User</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LoginName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CityId, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })*@
                @Html.DropDownListFor(model => model.CityId, (IEnumerable<SelectListItem>)ViewBag.Cities )


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Login")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Shivkumar/LoginSystem/LoginSystem/Views/Persons/Details.cshtml
@model LoginSystem.Models.Person

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/CustomLayout.cshtml";
}

@Html.Partial("PartialView1")
@{ 
    Html.RenderPartial("PartialView1");
}
<h2>WELCOME</h2>

<div>
    <h4> @Html.DisplayFor(model => model.LoginName)</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Update", "Edit", new { id = Model.LoginName }) |

    @*@Html.ActionLink("Logout", "Logout", new { /* id = Model.PrimaryKey */ }) |*@
    @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="Logout" value="Logout" class="btn btn-default" />
            </div>
        </div>*@
    @*@{
        Html.RenderPartial("Logout");

    }*@

    @Html.Partial("Logout")
</p>

Shivkumar/LoginSystem/LoginSystem/Views/Persons/Edit.cshtml
@model LoginSystem.Models.Person

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/CustomLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Person</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.LoginName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.DisplayFor(model => model.LoginName)*@
            @Html.EditorFor(model => model.LoginName, new
            {
                htmlAttributes = new
                {
                    @class = "form-control",
           @readonly = "readonly"
       }
       })
            @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.CityId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })*@
            @Html.DropDownListFor(model => model.CityId, (IEnumerable<SelectListItem>)ViewBag.Cities)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" name="update" value="Update" class="btn btn-default" />
        </div>
    </div>
    @Html.ActionLink("Home Page", "Details") |
</div>
}
<div>
    @using (Html.BeginForm("Logout", "Persons", FormMethod.Post))
    {
<input type="submit" value="Logout" class="btn btn-default" />}
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Shivkumar/LoginSystem/LoginSystem/Views/Persons/Login.cshtml
@model LoginSystem.Models.Person
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/CustomLayout.cshtml";
}

<h2>Login</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Person</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.LoginName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        
        <div class="col-md-10">
            @Html.CheckBoxFor(model => model.isActive) Remember me
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Login" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("New User", "Create")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



Shivkumar/LoginSystem/LoginSystem/Views/Persons/Logout.cshtml

<div>
    @using (Html.BeginForm("Logout", "Persons", FormMethod.Post))
    {
<input type="submit" value="Logout" class="btn btn-default" />}
</div>

Shivkumar/LoginSystem/LoginSystem/Views/Persons/PartialView1.cshtml

<marquee> Welcome Mahaling</marquee>